import { DiceItem } from '../types/dice.types';

export const INITIAL_DICE_ITEMS: DiceItem[] = [
  {
    id: 'dice_classic',
    name: 'Classic Bone',
    description: 'The standard bone dice trusted by ludo rollers for generations.',
    rarity: 'COMMON',
    level: 1,
    maxLevel: 5,
    isUnlocked: true,
    isEquipped: true,
    isFavorite: false,
    cost: {},
    attributes: {
      rollModifier: { name: 'Six Chance', value: 16.6, maxValue: 20 },
      goldBonus: { name: 'Gold Multiplier', value: 1.0, maxValue: 1.5 },
      xpBonus: { name: 'XP Multiplier', value: 1.0, maxValue: 1.5 },
    },
    visualEffectId: 'glow_default',
    soundEffectId: 'roll_classic',
    skinId: 'skin_classic_white',
  },
  {
    id: 'dice_lucky_star',
    name: 'Lucky Star',
    description: 'Infused with cosmic dust to slightly improve high rolls.',
    rarity: 'RARE',
    level: 1,
    maxLevel: 10,
    isUnlocked: false,
    isEquipped: false,
    isFavorite: false,
    cost: { coins: 5000 },
    attributes: {
      rollModifier: { name: 'Six Chance', value: 17.2, maxValue: 22 },
      goldBonus: { name: 'Gold Multiplier', value: 1.1, maxValue: 1.8 },
      xpBonus: { name: 'XP Multiplier', value: 1.1, maxValue: 1.8 },
    },
    visualEffectId: 'glow_blue',
    soundEffectId: 'roll_glass',
    skinId: 'skin_star_cyan',
  },
  {
    id: 'dice_volcano',
    name: 'Magma core',
    description: 'Forged in volcanic depths. Emits embers when rolled.',
    rarity: 'EPIC',
    level: 1,
    maxLevel: 10,
    isUnlocked: false,
    isEquipped: false,
    isFavorite: false,
    cost: { gems: 100 },
    attributes: {
      rollModifier: { name: 'Six Chance', value: 18.0, maxValue: 25 },
      goldBonus: { name: 'Gold Multiplier', value: 1.25, maxValue: 2.2 },
      xpBonus: { name: 'XP Multiplier', value: 1.25, maxValue: 2.2 },
    },
    visualEffectId: 'glow_red',
    soundEffectId: 'roll_heavy',
    skinId: 'skin_magma_orange',
  },
  {
    id: 'dice_emperor',
    name: 'Emperor Gold',
    description: 'Ornate gold frame with floating gold dust. Fits Ludo Royalty.',
    rarity: 'LEGENDARY',
    level: 1,
    maxLevel: 15,
    isUnlocked: false,
    isEquipped: false,
    isFavorite: false,
    cost: { gems: 250 },
    attributes: {
      rollModifier: { name: 'Six Chance', value: 19.5, maxValue: 28 },
      goldBonus: { name: 'Gold Multiplier', value: 1.5, maxValue: 3.0 },
      xpBonus: { name: 'XP Multiplier', value: 1.5, maxValue: 3.0 },
    },
    visualEffectId: 'glow_gold',
    soundEffectId: 'roll_royal',
    skinId: 'skin_gold_emperor',
  },
];
