import { DiceSkin } from '../types/skin.types';

export const INITIAL_DICE_SKINS: DiceSkin[] = [
  {
    id: 'skin_classic_white',
    name: 'Standard Ivory',
    description: 'The iconic white bone skin.',
    diceId: 'dice_classic',
    rarity: 'COMMON',
    assetPath: '/assets/images/dice/classic_white.png',
    glowColor: 'shadow-white/20',
    isUnlocked: true,
    cost: {},
  },
  {
    id: 'skin_star_cyan',
    name: 'Cosmic Cyan',
    description: 'Luminous teal skin that sparkles with star dust.',
    diceId: 'dice_lucky_star',
    rarity: 'RARE',
    assetPath: '/assets/images/dice/star_cyan.png',
    glowColor: 'shadow-cyan-400/40 border-cyan-400',
    particleEffect: 'sparks',
    isUnlocked: false,
    cost: { coins: 1500 },
  },
  {
    id: 'skin_magma_orange',
    name: 'Obsidian Fire',
    description: 'Black rock core with orange lava streams.',
    diceId: 'dice_volcano',
    rarity: 'EPIC',
    assetPath: '/assets/images/dice/magma_orange.png',
    glowColor: 'shadow-orange-500/50 border-orange-500',
    particleEffect: 'fire',
    isUnlocked: false,
    cost: { gems: 40 },
  },
  {
    id: 'skin_gold_emperor',
    name: 'Royal Aurum',
    description: 'Gold-plated outer rims with polished diamond indicators.',
    diceId: 'dice_emperor',
    rarity: 'LEGENDARY',
    assetPath: '/assets/images/dice/gold_emperor.png',
    glowColor: 'shadow-amber-400/60 border-yellow-400',
    particleEffect: 'gold_dust',
    isUnlocked: false,
    cost: { gems: 120 },
  },
];
