export const SOUND_ASSET_MAP = {
  DICE_SHAKE: 'dice_shake',
  DICE_ROLL: 'dice_roll',
  DICE_BOUNCE: 'dice_bounce',
  CRYSTAL_CLICK: 'crystal_click',
  GOLDEN_BELL: 'golden_bell',
  MOVE_TICK: 'move_tick',
  KILL: 'kill',
  HOME: 'home',
  VICTORY: 'victory',
  DEFEAT: 'defeat',
  MATCH_FOUND: 'match_found',
  BUTTON_HOVER: 'button_hover',
  POPUP: 'popup',
  REWARD: 'reward',
  XP: 'xp',
  COIN: 'coin',
  DIAMOND: 'diamond',
  TREASURE: 'treasure',
  CHEST: 'chest',
  SPIN: 'spin',
  DAILY_REWARD: 'daily_reward',
};
