export const DICE_PHYSICS_CONSTANTS = {
  GRAVITY: -9.81,
  BOUNCE_ELASTICITY: 0.65,
  AIR_RESISTANCE: 0.98,
  SPIN_FRICTION: 0.95,
  MIN_ROTATION_SPEED: 10,
  MAX_ROTATION_SPEED: 50,
  SHADOW_SCALE_FACTOR: 0.4,
};
