import { Quest } from '../types/xp.types';

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'q_daily_1',
    title: 'Daily Conquest',
    description: 'Win 1 Classic Game',
    xpReward: 350,
    coinReward: 200,
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    isClaimed: false,
    category: 'daily',
  },
  {
    id: 'q_daily_2',
    title: 'Chatterbox',
    description: 'Send 3 Chat Emotes in a match',
    xpReward: 150,
    gemReward: 5,
    targetCount: 3,
    currentCount: 2,
    isCompleted: false,
    isClaimed: false,
    category: 'daily',
  },
  {
    id: 'q_daily_3',
    title: 'Social Circle',
    description: 'Play 1 Private Match with friends',
    xpReward: 250,
    coinReward: 100,
    targetCount: 1,
    currentCount: 1,
    isCompleted: true,
    isClaimed: false,
    category: 'daily',
  },
  {
    id: 'q_weekly_1',
    title: 'Ludo Emperor',
    description: 'Win 5 Online Matches in any mode',
    xpReward: 1000,
    coinReward: 1000,
    gemReward: 10,
    targetCount: 5,
    currentCount: 2,
    isCompleted: false,
    isClaimed: false,
    category: 'weekly',
  },
  {
    id: 'q_weekly_2',
    title: 'Token Hunter',
    description: 'Capture 10 opponent tokens',
    xpReward: 750,
    coinReward: 500,
    targetCount: 10,
    currentCount: 6,
    isCompleted: false,
    isClaimed: false,
    category: 'weekly',
  },
  {
    id: 'q_weekly_3',
    title: 'High Roller',
    description: 'Roll a "6" fifty times in matches',
    xpReward: 600,
    coinReward: 300,
    targetCount: 50,
    currentCount: 34,
    isCompleted: false,
    isClaimed: false,
    category: 'weekly',
  },
];
