import { CurrencyItem, EventItem, GameModeItem, NavItem, UserHomeProfile } from '../types/home.types';

export class HomeData {
  static readonly PROFILE: UserHomeProfile = {
    id: 'usr_tasavvur',
    username: 'Tasavvur',
    displayName: 'Tasavvur',
    level: 25,
    xpPercent: 75,
    isOnline: true,
    country: '🇮🇳',
  };

  static readonly CURRENCIES: CurrencyItem[] = [
    {
      id: 'star',
      label: 'Stars',
      value: 50,
      icon: '⭐',
      badgeColor: 'text-amber-300',
      borderColor: 'border-amber-500/40',
      showPlus: true,
    },
    {
      id: 'energy',
      label: 'Energy',
      value: 10,
      icon: '⚡',
      badgeColor: 'text-yellow-300',
      borderColor: 'border-yellow-500/40',
      showPlus: true,
    },
    {
      id: 'coin',
      label: 'Coins',
      value: 1000,
      icon: '🪙',
      badgeColor: 'text-yellow-300',
      borderColor: 'border-amber-400/40',
      showPlus: true,
    },
    {
      id: 'gem',
      label: 'Gems',
      value: 30,
      icon: '💎',
      badgeColor: 'text-cyan-300',
      borderColor: 'border-cyan-500/40',
      showPlus: true,
    },
  ];

  static readonly EVENTS: EventItem[] = [
    {
      id: 'daily_reward',
      title: 'DAILY REWARD',
      subtitle: 'Claim Free Coins',
      icon: '🎁',
      requiredLevel: 1,
      isLocked: false,
      bgGradient: 'from-purple-900/90 to-purple-950/95',
      borderColor: 'border-purple-400/50',
      accentColor: 'text-amber-300',
      actionText: 'Claim Now',
    },
    {
      id: 'league_312',
      title: '312 LEAGUE',
      subtitle: 'Leaderboard Event',
      icon: '👑',
      requiredLevel: 5,
      isLocked: false,
      bgGradient: 'from-amber-600/90 via-purple-900/95 to-purple-950',
      borderColor: 'border-amber-400/70',
      accentColor: 'text-amber-300',
      timer: '2d 14h Left',
    },
    {
      id: 'lucky_spin',
      title: 'LUCKY SPIN',
      subtitle: 'Spin & Win',
      icon: '🎡',
      requiredLevel: 2,
      isLocked: false,
      bgGradient: 'from-purple-900/90 to-purple-950/95',
      borderColor: 'border-purple-400/50',
      accentColor: 'text-amber-300',
      actionText: 'Spin Now',
    },
  ];

  static readonly GAME_MODES: GameModeItem[] = [
    {
      id: '2p_classic',
      modeKey: '2P Classic',
      title: '2 PLAYER',
      subtitle: '1 vs 1 Ranked Match',
      icon: '🎲',
      isHero: true,
      bgGradient: 'card-2p-gradient',
      borderColor: 'border-[#ffd54f]',
      accentColor: 'text-amber-100',
    },
    {
      id: 'private_table',
      modeKey: 'Private Table',
      title: 'PRIVATE TABLE',
      subtitle: 'Play with Friends',
      icon: '🏠',
      bgGradient: 'card-private-gradient',
      borderColor: 'border-purple-400/60',
      accentColor: 'text-purple-200',
    },
    {
      id: 'team_up',
      modeKey: '2v2 Team Up',
      title: 'TEAM UP',
      subtitle: '2 vs 2 Match',
      icon: '👥',
      bgGradient: 'card-teamup-gradient',
      borderColor: 'border-teal-300/60',
      accentColor: 'text-teal-100',
    },
    {
      id: 'vip',
      modeKey: 'VIP Lounge',
      title: 'VIP ROOM',
      subtitle: 'High Stakes',
      icon: '👑',
      bgGradient: 'card-vip-gradient',
      borderColor: 'border-yellow-300/60',
      accentColor: 'text-yellow-100',
    },
    {
      id: 'streak_stars',
      modeKey: 'Streak Stars',
      title: 'STREAK STARS',
      subtitle: 'Win Streak Rewards',
      icon: '⭐',
      bgGradient: 'card-streak-gradient',
      borderColor: 'border-blue-300/60',
      accentColor: 'text-blue-100',
    },
    {
      id: 'tournament',
      modeKey: 'Tournament',
      title: 'TOURNAMENT',
      subtitle: 'Big Prizes',
      icon: '🏆',
      bgGradient: 'card-tournament-gradient',
      borderColor: 'border-pink-300/60',
      accentColor: 'text-pink-100',
    },
    {
      id: '4p',
      modeKey: '4P Classic',
      title: '4 PLAYER',
      subtitle: 'Play with All',
      icon: '🎲',
      bgGradient: 'card-4p-gradient',
      borderColor: 'border-lime-300/60',
      accentColor: 'text-lime-100',
    },
  ];

  static readonly NAV_ITEMS: NavItem[] = [
    { id: 'shop', label: 'SHOP', icon: '🛒', badge: 'NEW' },
    { id: 'friends', label: 'FRIENDS', icon: '👥' },
    { id: 'home', label: 'HOME', icon: '🏠', isHome: true },
    { id: 'rewards', label: 'REWARDS', icon: '🎁', badge: '2' },
    { id: 'profile', label: 'PROFILE', icon: '👤' },
  ];
}
